### ISSUE TITLE
rust ICE on nightly-2020-02-19

### ISSUE THREAD

**Issue by autumnjolitz** [ijl/orjson#57] opened 2020-02-20 21:14 UTC
I've posted the compiler bug at https://github.com/rust-lang/rust/issues/69327 but one of the changes in orjson or a dependency provokes a bug in the rustc compiler. idk what's really changed - I'm just fixing my builds to use an older precompiled orjson wheel from my private pypis 🙃

**Comment by pskopnik** [comment] 2020-02-21 12:35
Caused by rustc 1.43.0-nightly (7760cd0fb 2020-02-19) -> rustc 1.43.0-nightly (e620d0f33 2020-02-18) breaking while compiling encoding_rs.

 * hsivonen/encoding_rs#49
 * rust-lang/rust#69313

**Comment by ijl** [comment] 2020-02-24 12:48
This was fixed with nightly-2020-02-22.

**Closed by ijl** 2020-02-24 12:48 UTC
